Write design
cybozu-go/pod-security-admission pull request #1
Opened 2021-03-19 08:50 UTC by zoetrope

2021-03-19 09:32 UTC, tapih requested changes
Basically LGTM, but added some English reviews.

2021-03-19 09:32 UTC, tapih commented on README.md
> +`pod-security-admission` is a Kubernetes [admission webhooks](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) to ensure [Pod Security Standards](https://kub
"is composed of validation and mutating admission webhooks" looks better than "**a** ... webhook**s**"  
 for me.

2021-03-19 09:32 UTC, tapih commented on README.md
> +`pod-security-admission` is not a policy engine.
It would be more clear if you add "and users cannot write their own policies flexibly" at the end of the sentence, IMO.

2021-03-19 09:32 UTC, tapih commented on README.md
> +Admission webhook will not work to Pods to which this policy is applied.
Admission webhook does nothing to the Pods in namespaces with `Privileged` label.

2021-03-19 09:32 UTC, tapih commented on docs/configuration.md
> +By default, the following configuration are used:
configuration is used

2021-03-19 09:32 UTC, tapih commented on docs/configuration.md
> +For example, if you want to enforce `denyRunAsRoot` and `mutateRunAsNonRoot` in `Baseline`, you can specify the configuration as follows:
administrators can add the rules under the `Baseline` section

2021-03-19 09:43 UTC, umezawatakeshi reviewed
LGTM (except https://github.com/cybozu-go/pod-security-admission/pull/1#discussion_r597525347)

2021-03-22 04:18 UTC, ysksuzuki submitted a review, later dismissed
Looks good to me other than other reviewer's comments

2021-03-22 07:13 UTC, tapih approved these changes
LGTM

2021-03-22 07:13 UTC, merged