[wip][skip ci] Implement validators
cybozu-go/pod-security-admission pull request #3
Opened 2021-03-22 10:17 UTC by zoetrope

2021-03-26 01:44 UTC, ysksuzuki commented on cmd/root.go
>  	"io/ioutil"
`io/ioutil` is deprecated in go 1.16.  Use `os` package instead.

2021-03-29 05:09 UTC, tapih requested changes

2021-03-29 05:09 UTC, tapih commented on hooks/validators/deny_host_namespace.go
> +		errs = append(errs, field.Forbidden(p.Child("hostIPC"), "Host ips is not allowed to be used"))
`ips` should be `ipc`

2021-03-29 05:09 UTC, tapih commented on hooks/testdata/privileged/host-ipc.yaml
> +    test.pod-security.cybozu.com/message: "denied the request: spec.hostIPC: Forbidden: Host ips is not allowed to be used"
`ips` should be `ipc`

2021-03-29 05:09 UTC, tapih commented on Makefile
> +	source ${ENVTEST_ASSETS_DIR}/setup-envtest.sh; fetch_envtest_tools $(ENVTEST_ASSETS_DIR); setup_envtest_env $(ENVTEST_ASSETS_DIR); go test -v ./... -coverprofile cover.out
This might get developer's local environments dirty. I prefer to run it inside subshell.

2021-03-29 05:09 UTC, tapih commented on hooks/mutate_pod.go
> +	return &webhook.Admission{Handler: &podMutator{c, dec, mutators}}
Validating the `mutators` arg here might help us notice mistakes in configurations before actually applying pod-related manifests.

2021-03-29 05:09 UTC, tapih commented on hooks/mutate_pod.go
> +		mutator, ok := availableMutators[name]
Log for what kind of mutator is applied is helpful to know what happened exactly on Pods.

2021-03-29 05:09 UTC, tapih commented on hooks/validate_pod.go
>  	v := &podValidator{
The same as `mutat_pod.go`

2021-03-29 05:09 UTC, tapih commented on hooks/validate_pod.go
> +		validator, ok := availableValidators[name]
The same as `mutate_pod.go`.

2021-03-29 05:09 UTC, tapih commented on hooks/validators/deny_host_ports.go
> +func DenyHostPorts(ctx context.Context, pod *corev1.Pod) field.ErrorList {
The host port field in PSP accepts a range of ports to be allowed.
I'm not sure this is needed right now, but please consider it is needed or not.

2021-03-29 05:09 UTC, tapih commented on hooks/validators/deny_unsafe_capabilities.go
> +func DenyUnsafeCapabilities(ctx context.Context, pod *corev1.Pod) field.ErrorList {
The capabilities field in PSP accepts a list of capabilities to be allowed.
I'm not sure this is needed right now, but please consider it is needed or not.

2021-03-29 05:09 UTC, tapih commented on hooks/validators/deny_unsafe_capabilities.go
> +			if !containsString(defaultCapabilities, string(add)) {
If we use the set pattern with `map[string]struct{}`, we don't need to define `containsString`, but this line of code does not affect the performance of this webhoo badly, so doing it or not i's up to you.

2021-04-01 02:09 UTC, tapih approved these changes
LGTM

2021-04-01 03:04 UTC, merged