Docker
cybozu-go/pod-security-admission pull request #5
Opened 2021-03-25 10:22 UTC by zoetrope

2021-04-07 08:30 UTC, yokaze requested changes

2021-04-07 08:30 UTC, yokaze commented on .github/workflows/release.yaml
> +      - run: make build/install.yaml
```suggestion
      - run: make setup
      - run: make build/install.yaml
```

Possibly missing `make setup`.

```
/path/to/pod-security-admission/bin/kustomize build ./config/default > build/install.yaml
/bin/bash: /path/to/pod-security-admission/bin/kustomize: No such file or directory
make: *** [Makefile:77: build/install.yaml] Error 127
```

2021-04-07 08:30 UTC, yokaze commented on .github/workflows/release.yaml
> +        uses: actions/create-release@v1
`actions/create-release` is no more maintained, so its use should stand on an explicit decision.

2021-04-07 08:30 UTC, yokaze commented on .github/workflows/release.yaml
> +      - run: make build/install.yaml
`kustomize:` should be `$(KUSTOMIZE):`.

2021-04-07 08:30 UTC, yokaze commented on config/manager/manager.yaml
> +            limits:
We need to remove `limits`.

2021-04-08 08:20 UTC, zoetrope commented
Pre-release was successful!
https://github.com/cybozu-go/pod-security-admission/releases/tag/v0.0.1-alpha.0
https://quay.io/repository/cybozu/pod-security-admission?tab=tags

2021-04-08 08:23 UTC, yokaze approved these changes
LGTM

2021-04-08 08:29 UTC, merged